#pragma once
#include "filesystem.h"
#define SET_LOCALE_ENVIRON(name, default_value) ((!ngs::fs::environment_get_variable(name).empty()) ? ngs::fs::environment_get_variable(name).c_str() : std::string(default_value).c_str())
#ifndef IFD_QUICK_ACCESS
#define IFD_QUICK_ACCESS SET_LOCALE_ENVIRON("IMGUI_QUICK_ACCESS", "主文件夹")
#endif
#ifndef IFD_THIS_PC
#define IFD_THIS_PC SET_LOCALE_ENVIRON("IMGUI_THIS_PC", "此电脑")
#endif
#ifndef IFD_ALL_FILES
#define IFD_ALL_FILES SET_LOCALE_ENVIRON("IMGUI_ALL_FILES", "所有文件")
#endif
#ifndef IFD_NAME
#define IFD_NAME SET_LOCALE_ENVIRON("IMGUI_NAME", "名称")
#endif
#ifndef IFD_DATE_MODIFIED
#define IFD_DATE_MODIFIED SET_LOCALE_ENVIRON("IMGUI_DATE_MODIFIED", "修改日期")
#endif
#ifndef IFD_SIZE
#define IFD_SIZE SET_LOCALE_ENVIRON("IMGUI_SIZE", "大小")
#endif
#ifndef IFD_NEW_FILE
#define IFD_NEW_FILE SET_LOCALE_ENVIRON("IMGUI_NEW_FILE", "新建文件")
#endif
#ifndef IFD_NEW_DIRECTORY
#define IFD_NEW_DIRECTORY SET_LOCALE_ENVIRON("IMGUI_NEW_DIRECTORY", "新建文件夹")
#endif
#ifndef IFD_DELETE
#define IFD_DELETE SET_LOCALE_ENVIRON("IMGUI_DELETE", "删除")
#endif
#ifndef IFD_ARE_YOU_SURE
#define IFD_ARE_YOU_SURE SET_LOCALE_ENVIRON("IMGUI_ARE_YOU_SURE", "确定吗？")
#endif
#ifndef IFD_OVERWRITE_FILE
#define IFD_OVERWRITE_FILE SET_LOCALE_ENVIRON("IMGUI_OVERWRITE_FILE", "覆盖文件吗？")
#endif
#ifndef IFD_ENTER_FILE_NAME
#define IFD_ENTER_FILE_NAME SET_LOCALE_ENVIRON("IMGUI_ENTER_FILE_NAME", "输入文件名")
#endif
#ifndef IFD_ENTER_DIRECTORU_NAME
#define IFD_ENTER_DIRECTORY_NAME SET_LOCALE_ENVIRON("IMGUI_ENTER_DIRECTORY_NAME", "输入目录名")
#endif
#ifndef IFD_ARE_YOU_SURE_YOU_WANT_TO_DELETE
#define IFD_ARE_YOU_SURE_YOU_WANT_TO_DELETE SET_LOCALE_ENVIRON("IMGUI_ARE_YOU_SURE_YOU_WANT_TO_DELETE", "确定要删除 %s 吗？")
#endif
#ifndef IFD_ARE_YOU_SURE_YOU_WANT_TO_OVERWRITE
#define IFD_ARE_YOU_SURE_YOU_WANT_TO_OVERWRITE SET_LOCALE_ENVIRON("IMGUI_ARE_YOU_SURE_YOU_WANT_TO_OVERWRITE", "确定要覆盖 %s 吗？")
#endif
#ifndef IFD_YES
#define IFD_YES SET_LOCALE_ENVIRON("IMGUI_YES", "是")
#endif
#ifndef IFD_NO
#define IFD_NO SET_LOCALE_ENVIRON("IMGUI_NO", "否")
#endif
#ifndef IFD_OK
#define IFD_OK SET_LOCALE_ENVIRON("IMGUI_OK", "确定")
#endif
#ifndef IFD_CANCEL
#define IFD_CANCEL SET_LOCALE_ENVIRON("IMGUI_CANCEL", "取消")
#endif
#ifndef IFD_SEARCH
#define IFD_SEARCH SET_LOCALE_ENVIRON("IMGUI_SEARCH", "搜索")
#endif
#ifndef IFD_FILE_NAME_WITH_COLON
#define IFD_FILE_NAME_WITH_COLON SET_LOCALE_ENVIRON("IMGUI_FILE_NAME_WITH_COLON", "文件名：")
#endif
#ifndef IFD_FILE_NAME_WITHOUT_COLON
#define IFD_FILE_NAME_WITHOUT_COLON SET_LOCALE_ENVIRON("IMGUI_FILE_NAME_WITHOUT_COLON", "文件名")
#endif
#ifndef IFD_SAVE
#define IFD_SAVE SET_LOCALE_ENVIRON("IMGUI_SAVE", "保存")
#endif
#ifndef IFD_OPEN
#define IFD_OPEN SET_LOCALE_ENVIRON("IMGUI_OPEN", "打开")
#endif
