#!/bin/sh
cd "${0%/*}";
if [ `uname` = "Darwin" ]; then
  env IMGUI_DIALOG_WIDTH=720 IMGUI_DIALOG_HEIGHT=380 IMGUI_DIALOG_THEME=2 IMGUI_TEXT_COLOR_0=1 IMGUI_TEXT_COLOR_1=1 IMGUI_TEXT_COLOR_2=1 IMGUI_HEAD_COLOR_0=0.35 IMGUI_HEAD_COLOR_1=0.35 IMGUI_HEAD_COLOR_2=0.35 IMGUI_AREA_COLOR_0=0.05 IMGUI_AREA_COLOR_1=0.05 IMGUI_AREA_COLOR_2=0.05 IMGUI_BODY_COLOR_0=1 IMGUI_BODY_COLOR_1=1 IMGUI_BODY_COLOR_2=1 IMGUI_POPS_COLOR_0=0.07 IMGUI_POPS_COLOR_1=0.07 IMGUI_POPS_COLOR_2=0.07 ../filedialogs --get-open-filename "Portable Network Graphic (*.png)|*.png|Graphic Interchange Format (*.gif)|*.gif" "Untitled.png";
else
  env IMGUI_DIALOG_PARENT=`xdotool getactivewindow` IMGUI_DIALOG_WIDTH=720 IMGUI_DIALOG_HEIGHT=380 IMGUI_DIALOG_THEME=2 IMGUI_TEXT_COLOR_0=1 IMGUI_TEXT_COLOR_1=1 IMGUI_TEXT_COLOR_2=1 IMGUI_HEAD_COLOR_0=0.35 IMGUI_HEAD_COLOR_1=0.35 IMGUI_HEAD_COLOR_2=0.35 IMGUI_AREA_COLOR_0=0.05 IMGUI_AREA_COLOR_1=0.05 IMGUI_AREA_COLOR_2=0.05 IMGUI_BODY_COLOR_0=1 IMGUI_BODY_COLOR_1=1 IMGUI_BODY_COLOR_2=1 IMGUI_POPS_COLOR_0=0.07 IMGUI_POPS_COLOR_1=0.07 IMGUI_POPS_COLOR_2=0.07 ../filedialogs --get-open-filename "Portable Network Graphic (*.png)|*.png|Graphic Interchange Format (*.gif)|*.gif" "Untitled.png";
fi
